# Generated by Django 3.2.16 on 2024-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240507_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads_model', verbose_name='Изображения'),
        ),
    ]
