# Generated by Django 3.2.16 on 2024-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads_posts/%Y/%m/%d/', verbose_name='Изображения'),
        ),
    ]
