# Generated by Django 3.2.16 on 2024-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240510_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/', verbose_name='Изображениe'),
        ),
    ]
